[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001", "lockscreen-widget-0000000000000002" ]

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 350.0
    cx = 731.5
    cy = 502.0
    output = "eDP-1"
    placement_height = 914.0
    placement_width = 1463.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.0
        background_radius = 0.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 0.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        # show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        # show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 40.0
    box_width = 0.0
    cx = 731.5
    cy = 20.0
    output = "eDP-1"
    placement_height = 914.0
    placement_width = 1463.0
    rotation = 0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 1447.5
    cy = 897.0
    output = "eDP-1"
    placement_height = 914.0
    placement_width = 1463.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = true
        font_family = "C059"
        glyph = "power"
        variant = "default"
